trigger:
- master

resources:
  repositories:
  - repository: 'CreateTicketAzureFunction'
    type: git
    name: 'GCExchange/CreateTicketAzureFunction'
pool: TBS Linux Self Hosted
jobs:
  - job: sync
    uses:
     repositories:
       - 'CreateTicketAzureFunction'
    steps:
    - script: |
        echo Sync azure repo
        git clone --bare https://tbs-sct:$(System.AccessToken)@dev.azure.com/tbs-sct/GCExchange/_git/$REPO_NAME Sync_directory
        cd Sync_directory
        git remote add --mirror=fetch upstream https://github.com/gcxchange-gcechange/$REPO_NAME
        git fetch upstream --tags
        git push origin --all
      env:
        REPO_NAME: "CreateTicketAzureFunction"
      displayName: 'Sync repo'
